import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[env]
TERM = "xterm-256color"
